name: build-test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.3.0
    - uses: actions/setup-node@v4.4.0
      with:
         node-version: '22.20.0'
    - name: use yarn
      run: |
       yarn install
       yarn build
       yarn generate